name: lab_pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=2,<3
  - scipy
  - pandas>=2,<3
  - scikit-learn
  - scikit-image
  - matplotlib
  - tifffile
  - imageio
  - pillow
  - tqdm
  - pytorch
  - torchvision
  - pyqt>=6,<7
  - pip
  - pip:
      - -e .
      - opencv-python-headless==4.13.0.92
      - suite2p==1.1.0
      - harp-python==0.4.1
      - circle-fit==0.2.1
      - pynwb==3.1.3
